# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ludovic Lardies
email: ludovic.lardies@icloud.com
url: lardies.fr
baseurl:
paginate: 3
paginate_path: /projets/page:num
gems:
  - jekyll-paginate

# Build settings
markdown: kramdown

# Meta settigs
keywords: Ruby on Rails, ROR, Python, CV, Résumé, Lardies, Ingénieur informatique, Paris
author: Ludovic Lardies
description: CV de Ludovic Lardies
