theme: jekyll-theme-time-machine
description: 'Ingénieur logiciel de 27 ans de Paris, spécialisé en backend et ops.[Linkedin](https://www.linkedin.com/in/lardies/) [email](mailto:ludoviclrds+cv@gmail.com'
title: Ludovic Lardies
